apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    {{- include "nexshop.labels" . | nindent 4 }}
    app: backend
data:
  database-name: {{ .Values.backend.config.databaseName | quote }}
  project-name: {{ .Values.backend.config.projectName | quote }}
