apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    {{- include "nexshop.labels" . | nindent 4 }}
    app: backend
type: Opaque
data:
  mongodb-url: {{ .Values.backend.secrets.mongodbUrl | b64enc | quote }}
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | b64enc | quote }}
