apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "nexshop.labels" . | nindent 4 }}
    app: frontend
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      name: http
  selector:
    app: frontend
  type: {{ .Values.frontend.service.type }}
