apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    {{- include "nexshop.labels" . | nindent 4 }}
    app: mongodb
spec:
  serviceName: "mongodb-headless"
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        {{- include "nexshop.selectorLabels" . | nindent 8 }}
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.service.targetPort }}
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          {{- if .Values.mongodb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: mongodb-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
