apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    {{- include "nexshop.labels" . | nindent 4 }}
    app: mongodb
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.secrets.rootUsername | b64enc | quote }}
  mongo-root-password: {{ .Values.mongodb.secrets.rootPassword | b64enc | quote }}
